# Generated by Django 6.0.3 on 2026-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
